### ISSUE TITLE
activate github pages

### ISSUE THREAD

**Issue by certik** [lfortran/wasm_builds#2]
It seems GitHub has changed how pages are deployed.

**Comment by certik** [comment]
Ok, I just enabled it, from the `docs` branch.

**Comment by ubaidsk** [comment]
It seems the GitHub pages for this repository is not updating. The last job executed is https://github.com/lfortran/wasm_builds/actions/runs/3528979264 which is for commit 306c062f3081cdc558d010300d61da255c2b514f. There is no job executing or executed for commit 3c75b65ecdba1fba47bc376efc4f83f05d25f236.

**Comment by ubaidsk** [comment]
>It seems the GitHub pages for this repository is not updating. The last job executed is https://github.com/lfortran/wasm_builds/actions/runs/3528979264 which is for commit https://github.com/lfortran/wasm_builds/commit/306c062f3081cdc558d010300d61da255c2b514f. There is no job executing or executed for commit https://github.com/lfortran/wasm_builds/commit/3c75b65ecdba1fba47bc376efc4f83f05d25f236.

This seems strange. Does GitHub Pages for this repository got deactivated (again). @certik Please could you possibly look into it? Or did this repository surpass some size limit due to which the CI at this repository is not working?
